"""
Return engines.

Every engine exposes the same interface:

    engine.sample(n_paths, n_years, seed) -> ndarray (n_paths, n_years)
        annual REAL total returns as simple returns (0.05 == +5% real)

Two engines, deliberately:

  HistoricalBootstrap — block bootstrap over an annual real return history.
      Auditable, boring, defensible. Preserves whatever sequence structure
      exists inside a block. This is the DEFAULT.

  NeuralSDE — Kev's neural-sde package. Fits state-dependent drift and
      diffusion to a DAILY price series, simulates daily, aggregates to
      annual. Labelled, secondary, never the default.

=========================== DATA HEALTH WARNING ===========================
This module has NO real market data behind it. The long-run UK series that
would be good enough to ship (Barclays Equity Gilt Study, DMS/UBS Yearbook)
are proprietary, and no licence-clean alternative has been secured yet —
see docs/DATA-SOURCING.md for the full assessment.

So the market history here is SYNTHETIC, generated by make_synthetic_market()
below. That is not a fudge, it is the right first test: we know the true
data-generating process, so we can ask whether the neural engine recovers
it and whether recovering it changes retirement outcomes. Ground truth
first, real data second.

Do NOT read any number produced from this data as a statement about real
markets. Swapping in real annual UK real total returns means replacing
ONE function: load_history().
===========================================================================
"""

from __future__ import annotations

import numpy as np


# --------------------------------------------------------------------------
# Synthetic ground-truth market
# --------------------------------------------------------------------------

def make_synthetic_market(
    n_years: int = 100,
    steps_per_year: int = 252,
    mu_real: float = 0.05,
    base_vol: float = 0.16,
    seed: int = 20260815,
) -> np.ndarray:
    """
    Daily real price index with the two features that actually matter for
    sequence-of-returns risk, and which a lognormal random walk has neither of:

      1. Volatility clustering (GARCH(1,1)-style) — bad days cluster into
         bad years, which is what makes a bad retirement decade possible.
      2. Leverage effect — volatility rises after falls, so drawdowns are
         deeper and slower to recover than a symmetric model implies.

    Returned as a price level series (levels, not returns) because that is
    what neural_sde.fit() consumes.
    """
    rng = np.random.default_rng(seed)
    n = n_years * steps_per_year
    dt = 1.0 / steps_per_year

    # GARCH(1,1) with a leverage term, parameterised so the unconditional
    # daily vol reproduces base_vol annualised.
    omega_scale = base_vol ** 2 * dt
    alpha, beta, lev = 0.06, 0.90, 0.06
    omega = omega_scale * (1.0 - alpha - beta - lev / 2.0)

    var = np.empty(n)
    ret = np.empty(n)
    var[0] = omega_scale
    drift = (mu_real - 0.5 * base_vol ** 2) * dt

    # Student-t innovations (fat tails), standardised to unit variance.
    dof = 5.0
    z = rng.standard_t(dof, size=n) / np.sqrt(dof / (dof - 2.0))

    for t in range(n):
        if t > 0:
            prev = ret[t - 1] - drift
            neg = 1.0 if prev < 0 else 0.0
            var[t] = omega + alpha * prev ** 2 + lev * neg * prev ** 2 \
                + beta * var[t - 1]
        ret[t] = drift + np.sqrt(var[t]) * z[t]

    return 100.0 * np.exp(np.cumsum(ret))


def load_history(seed: int = 20260815) -> tuple[np.ndarray, np.ndarray]:
    """
    THE ONE FUNCTION TO REPLACE WITH REAL DATA.

    Returns (daily_prices, annual_real_returns).
    """
    daily = make_synthetic_market(seed=seed)
    annual_idx = daily[::252]
    annual = annual_idx[1:] / annual_idx[:-1] - 1.0
    return daily, annual


# --------------------------------------------------------------------------
# The return CONVENTION — the one place this formula is written
# --------------------------------------------------------------------------
#
# "5% expected return" is ambiguous, and at the shipped defaults the ambiguity
# is worth 12.3pp of success rate (41a, measured 1 September 2026).
#
#   "geo"  the figure is the GEOMETRIC mean — what the pot actually compounds
#          at. Volatility then costs the compound return nothing, because the
#          median growth rate is pinned to the user's own number.
#   "ari"  the figure is the ARITHMETIC mean — the average of the yearly
#          returns. Variance drag then eats sigma^2/2 of it: at vol 15% that
#          is 1.125pp of return a year.
#
# This has existed in the browser since the calculator shipped
# (public/index.html:774) and did NOT exist here until 1 September 2026, so
# the arithmetic branch of the shipped calculator was cross-checked against
# nothing for as long as it has been live. That is 10b and 10c with the
# engines swapped — a parameter the JS can express and the Python cannot —
# and 31's literal audit could not have found it, because it only swept in
# the other direction (JS literal -> Python parameter). Sweep both ways.
#
# Written ONCE here and referenced from FCAPrescribed.sample and from
# verify_web.py, rather than restated in each (10f).

CONVENTIONS = ("geo", "ari")


def standard_normals(n_paths: int, n_years: int,
                     seed: int | None = None) -> np.ndarray:
    """Standard normals with the sampling error in the mean removed.

    MIRRORS normals() in public/index.html, which standardises over the whole
    flattened draw of N*years values rather than per year — so this does the
    same, over the whole matrix. The two engines run different RNG streams, so
    this is what makes their answers comparable to a fraction of a point
    instead of to the ~0.35pp standard error of 20,000 raw paths.
    """
    rng = np.random.default_rng(seed)
    z = rng.standard_normal((n_paths, n_years))
    return (z - z.mean()) / z.std()


def lognormal_real(real: float, vol: float, z: np.ndarray,
                   conv: str = "geo") -> np.ndarray:
    """Annual REAL returns from standardised normals, under a stated convention.

    MIRRORS public/index.html:774 exactly:

        const mu = Math.log1p(P.real) - (P.conv==="ari" ? .5*P.vol*P.vol : 0);
        ...  expm1(mu + vol*z)

    log1p/expm1 rather than log/exp is not decoration: the sloppier
    exp(r) - 1 form proposed in 41 was measured at 0.044pp of success rate at
    the default settings, in the wrong direction.

    `conv` is VALIDATED here, even though the browser silently treats anything
    that is not "ari" as geometric. The asymmetry is deliberate. The browser
    reads this from a two-option <select> and cannot be handed a typo; every
    caller on this side builds its config BY HAND, which is exactly how 41a
    stayed invisible — nine hand-written call sites, every one of them
    "geo". A mistyped convention must raise, not quietly run the other branch
    (10h: an assertion that the excluded failure mode can also satisfy is not
    an assertion).
    """
    if conv not in CONVENTIONS:
        raise ValueError(f"conv must be one of {CONVENTIONS}, got {conv!r}")
    mu = np.log1p(real) - (0.5 * vol * vol if conv == "ari" else 0.0)
    return np.expm1(mu + vol * z)

# --------------------------------------------------------------------------
# Engine 1 — historical block bootstrap (the default)
# --------------------------------------------------------------------------

class HistoricalBootstrap:
    """
    Block bootstrap over an annual real return history.

    block_years=1 gives i.i.d. resampling and destroys all sequence
    structure. block_years>1 preserves runs of good and bad years inside
    each block, which is the whole point: sequence-of-returns risk is about
    bad years arriving consecutively and early.
    """

    name = "Historical bootstrap"
    is_default = True

    def __init__(self, annual_returns: np.ndarray, block_years: int = 5):
        self.history = np.asarray(annual_returns, dtype=float)
        self.block_years = int(block_years)
        if len(self.history) < self.block_years:
            raise ValueError("history shorter than block length")

    def sample(self, n_paths: int, n_years: int, seed: int | None = None):
        rng = np.random.default_rng(seed)
        h, b = self.history, self.block_years
        n_blocks = int(np.ceil(n_years / b))
        starts = rng.integers(0, len(h) - b + 1, size=(n_paths, n_blocks))
        offsets = np.arange(b)
        idx = (starts[:, :, None] + offsets[None, None, :]).reshape(n_paths, -1)
        return h[idx][:, :n_years]

    def describe(self):
        h = self.history
        return (f"{self.name}: {len(h)} annual observations, "
                f"{self.block_years}-year blocks, "
                f"mean {h.mean():+.2%}, sd {h.std(ddof=1):.2%}")


# --------------------------------------------------------------------------
# Engine 2 — neural SDE (labelled second layer)
# --------------------------------------------------------------------------

class NeuralSDE:
    """
    Wraps neural_sde. Fits at daily frequency where the package is
    calibrated, simulates daily, then aggregates to annual.

    IMPORTANT — drift is NOT taken from the model. The package's own
    documentation states that drift recovery is not usable at daily
    sampling frequency (signal-to-noise limit on a single path). Over a
    30-year horizon drift dominates everything, so leaving it to a learned
    black box would be both unreliable and untransparent.

    Instead: the model supplies the PATH SHAPE — volatility clustering,
    state dependence, the texture of drawdowns — and the annual log drift
    is then rescaled to a user-set assumption (`target_real_drift`). The
    user owns the number that matters; the model contributes the structure
    nobody else models.
    """

    name = "Neural SDE"
    is_default = False

    def __init__(self, daily_prices: np.ndarray, target_real_drift: float = 0.05,
                 steps_per_year: int = 252, model: str = "neural"):
        from neural_sde import fit
        self.steps_per_year = steps_per_year
        self.target_real_drift = float(target_real_drift)
        self.dt = 1.0 / steps_per_year
        self.fitted = fit(np.asarray(daily_prices, float), dt=self.dt, model=model)
        self.model_kind = self.fitted.kind

    def sample(self, n_paths: int, n_years: int, seed: int | None = None,
               batch: int = 250):
        from neural_sde import forecast
        horizon = n_years * self.steps_per_year
        out = np.empty((n_paths, n_years))
        done = 0
        b = 0
        while done < n_paths:
            k = min(batch, n_paths - done)
            fc = forecast(
                self.fitted, horizon=horizon, n_paths=k,
                antithetic=False, engine="euler",
                seed=None if seed is None else seed + b,
            )
            paths = np.asarray(fc.paths)
            if paths.shape[0] != k:          # (steps, paths) orientation
                paths = paths.T
            yearly = paths[:, ::self.steps_per_year][:, :n_years + 1]
            out[done:done + k] = yearly[:, 1:] / yearly[:, :-1] - 1.0
            done += k
            b += 1
            del fc, paths

        # Rescale annual log drift to the user's assumption, leaving the
        # path-shape structure the model learned intact.
        log_r = np.log1p(np.clip(out, -0.999, None))
        out = np.expm1(log_r - log_r.mean() + np.log1p(self.target_real_drift)
                       - 0.5 * log_r.var())
        return out

    def describe(self):
        return (f"{self.name}: fitted kind={self.model_kind}, "
                f"daily dt=1/{self.steps_per_year}, drift rescaled to "
                f"{self.target_real_drift:+.2%} real (user assumption, "
                f"NOT learned)")


# --------------------------------------------------------------------------
# Engine 3 — FCA projection rates (no dataset required)
# --------------------------------------------------------------------------

class FCAPrescribed:
    """
    Return engine built on the FCA's own standardised projection rates, so
    it needs NO historical dataset and therefore has NO licensing problem.

    NAMING, corrected 2026-08-20: these are NOT "prescribed" rates, and this
    class is misnamed. COBS 13 Annex 2 2.3R sets MAXIMUM rates — a firm's
    intermediate rate "must accurately reflect the investment potential of
    each of the product's underlying investment options" and "must not exceed"
    the table below. Only the INFLATION rates in 2.5R are prescribed as fixed
    values. The class name is kept so existing code and saved scripts still
    run; the user-facing `name` below is accurate.

    Consequence worth stating plainly: 5% is the HIGHEST INTERMEDIATE rate a
    firm may use for a personal pension, and the firm is expected to justify it
    against the actual underlying investments. It is a cap on the central case,
    NOT the top of the permitted range — 1.1R requires a compliant projection to
    show lower, intermediate and higher, so 2/5/8 is the full span and 5 is its
    middle. Do not describe the default as "optimistic": the cap is uniform
    across all personal pensions regardless of asset mix, so for an
    equity-heavy pot it may well be an understatement.

    COBS 13 Annex 2 2.3R — MAXIMUM nominal rates for a personal or stakeholder
    pension:                     lower 2%   intermediate 5%   higher 8%
    COBS 13 Annex 2 2.5R — price inflation, prescribed as fixed values:
                                 lower 0%   intermediate 2%   higher 4%

    Deflating each return by the INTERMEDIATE inflation rate (2%) gives the
    real rates this engine uses:

        lower  (1.02/1.02) - 1 = 0.00% real
        centre (1.05/1.02) - 1 = 2.94% real
        higher (1.08/1.02) - 1 = 5.88% real

    CORRECTED 2026-08-20: that pairing is NOT an interpretation, as this
    docstring previously claimed. COBS 13 Annex 2 1.2R requires a personal
    pension projection to "be in real terms" and to be calculated using "the
    intermediate rate of price inflation, in accordance with COBS 13 Annex 2
    2.5R". Deflating the nominal rate by 2% is the Handbook's own construction.
    It stays exposed as a parameter anyway, so a user can model something else.

    IMPORTANT: the FCA caps RETURNS and says nothing at all about VOLATILITY.
    `vol` below is an assumption with no regulatory backing, and it is the
    weakest number in this engine. It must be surfaced to the user, not buried.

    Source: https://handbook.fca.org.uk/handbook/COBS/13/Annex2.html
    Checked: 2026-08-15, re-read 2026-08-20. The maximum rates are
    periodically reviewed — re-check against the live Handbook before relying
    on them.
    """

    name = "FCA projection rates (Handbook maximum)"
    is_default = False

    NOMINAL = {"lower": 0.02, "centre": 0.05, "higher": 0.08}
    INFLATION = {"lower": 0.00, "centre": 0.02, "higher": 0.04}
    SOURCE = ("FCA Handbook COBS 13 Annex 2 2.3R (maximum rates) / 2.5R "
              "(prescribed inflation), checked 2026-08-20")

    def __init__(self, scenario: str = "centre", vol: float = 0.15,
                 inflation_scenario: str = "centre", conv: str = "geo"):
        if scenario not in self.NOMINAL:
            raise ValueError(f"scenario must be one of {list(self.NOMINAL)}")
        # 41a. Default "geo" reproduces every figure this engine produced
        # before 1 September 2026 exactly — the og card and verify_household
        # both construct it without naming a convention. Validated at
        # CONSTRUCTION as well as at sample(), so a typo fails on the line
        # that contains it rather than several calls later.
        if conv not in CONVENTIONS:
            raise ValueError(f"conv must be one of {CONVENTIONS}, got {conv!r}")
        self.scenario = scenario
        self.conv = conv
        self.vol = float(vol)
        self.nominal = self.NOMINAL[scenario]
        self.inflation = self.INFLATION[inflation_scenario]
        self.real = (1 + self.nominal) / (1 + self.inflation) - 1

    def sample(self, n_paths: int, n_years: int, seed: int | None = None):
        # Lognormal. Under the default "geo" convention the GEOMETRIC mean is
        # pinned to self.real, so the user's stated assumption is what the pot
        # actually compounds at rather than an arithmetic mean that quietly
        # overshoots it. Under "ari" the stated figure is the arithmetic mean
        # and variance drag is taken off it — see lognormal_real, which is the
        # same expression the browser evaluates.
        z = standard_normals(n_paths, n_years, seed)
        return lognormal_real(self.real, self.vol, z, self.conv)

    def scenarios(self, n_years: int):
        """The three deterministic FCA projections, real terms."""
        out = {}
        for k, nom in self.NOMINAL.items():
            r = (1 + nom) / (1 + self.inflation) - 1
            out[k] = np.full((1, n_years), r)
        return out

    def describe(self):
        return (f"{self.name}: {self.scenario} scenario, {self.nominal:.0%} "
                f"nominal less {self.inflation:.0%} inflation = "
                f"{self.real:+.2%} real, treated as "
                f"{'a geometric' if self.conv == 'geo' else 'an arithmetic'} mean; "
                f"vol {self.vol:.0%} "
                f"(NOT set by the FCA — user assumption). {self.SOURCE}")
