"""
Return engines.

Every engine exposes the same interface:

    engine.sample(n_paths, n_years, seed) -> ndarray (n_paths, n_years)
        annual REAL total returns as simple returns (0.05 == +5% real)

Two engines, deliberately:

  HistoricalBootstrap — block bootstrap over an annual real return history.
      Auditable, boring, defensible. Preserves whatever sequence structure
      exists inside a block. This is the DEFAULT.

  NeuralSDE — Kev's neural-sde package. Fits state-dependent drift and
      diffusion to a DAILY price series, simulates daily, aggregates to
      annual. Labelled, secondary, never the default.

=========================== DATA HEALTH WARNING ===========================
This module has NO real market data behind it. The long-run UK series that
would be good enough to ship (Barclays Equity Gilt Study, DMS/UBS Yearbook)
are proprietary, and no licence-clean alternative has been secured yet —
see docs/DATA-SOURCING.md for the full assessment.

So the market history here is SYNTHETIC, generated by make_synthetic_market()
below. That is not a fudge, it is the right first test: we know the true
data-generating process, so we can ask whether the neural engine recovers
it and whether recovering it changes retirement outcomes. Ground truth
first, real data second.

Do NOT read any number produced from this data as a statement about real
markets. Swapping in real annual UK real total returns means replacing
ONE function: load_history().
===========================================================================
"""

from __future__ import annotations

import numpy as np


# --------------------------------------------------------------------------
# Synthetic ground-truth market
# --------------------------------------------------------------------------

def make_synthetic_market(
    n_years: int = 100,
    steps_per_year: int = 252,
    mu_real: float = 0.05,
    base_vol: float = 0.16,
    seed: int = 20260815,
) -> np.ndarray:
    """
    Daily real price index with the two features that actually matter for
    sequence-of-returns risk, and which a lognormal random walk has neither of:

      1. Volatility clustering (GARCH(1,1)-style) — bad days cluster into
         bad years, which is what makes a bad retirement decade possible.
      2. Leverage effect — volatility rises after falls, so drawdowns are
         deeper and slower to recover than a symmetric model implies.

    Returned as a price level series (levels, not returns) because that is
    what neural_sde.fit() consumes.
    """
    rng = np.random.default_rng(seed)
    n = n_years * steps_per_year
    dt = 1.0 / steps_per_year

    # GARCH(1,1) with a leverage term, parameterised so the unconditional
    # daily vol reproduces base_vol annualised.
    omega_scale = base_vol ** 2 * dt
    alpha, beta, lev = 0.06, 0.90, 0.06
    omega = omega_scale * (1.0 - alpha - beta - lev / 2.0)

    var = np.empty(n)
    ret = np.empty(n)
    var[0] = omega_scale
    drift = (mu_real - 0.5 * base_vol ** 2) * dt

    # Student-t innovations (fat tails), standardised to unit variance.
    dof = 5.0
    z = rng.standard_t(dof, size=n) / np.sqrt(dof / (dof - 2.0))

    for t in range(n):
        if t > 0:
            prev = ret[t - 1] - drift
            neg = 1.0 if prev < 0 else 0.0
            var[t] = omega + alpha * prev ** 2 + lev * neg * prev ** 2 \
                + beta * var[t - 1]
        ret[t] = drift + np.sqrt(var[t]) * z[t]

    return 100.0 * np.exp(np.cumsum(ret))


def load_history(seed: int = 20260815) -> tuple[np.ndarray, np.ndarray]:
    """
    THE ONE FUNCTION TO REPLACE WITH REAL DATA.

    Returns (daily_prices, annual_real_returns).
    """
    daily = make_synthetic_market(seed=seed)
    annual_idx = daily[::252]
    annual = annual_idx[1:] / annual_idx[:-1] - 1.0
    return daily, annual


# --------------------------------------------------------------------------
# Engine 1 — historical block bootstrap (the default)
# --------------------------------------------------------------------------

class HistoricalBootstrap:
    """
    Block bootstrap over an annual real return history.

    block_years=1 gives i.i.d. resampling and destroys all sequence
    structure. block_years>1 preserves runs of good and bad years inside
    each block, which is the whole point: sequence-of-returns risk is about
    bad years arriving consecutively and early.
    """

    name = "Historical bootstrap"
    is_default = True

    def __init__(self, annual_returns: np.ndarray, block_years: int = 5):
        self.history = np.asarray(annual_returns, dtype=float)
        self.block_years = int(block_years)
        if len(self.history) < self.block_years:
            raise ValueError("history shorter than block length")

    def sample(self, n_paths: int, n_years: int, seed: int | None = None):
        rng = np.random.default_rng(seed)
        h, b = self.history, self.block_years
        n_blocks = int(np.ceil(n_years / b))
        starts = rng.integers(0, len(h) - b + 1, size=(n_paths, n_blocks))
        offsets = np.arange(b)
        idx = (starts[:, :, None] + offsets[None, None, :]).reshape(n_paths, -1)
        return h[idx][:, :n_years]

    def describe(self):
        h = self.history
        return (f"{self.name}: {len(h)} annual observations, "
                f"{self.block_years}-year blocks, "
                f"mean {h.mean():+.2%}, sd {h.std(ddof=1):.2%}")


# --------------------------------------------------------------------------
# Engine 2 — neural SDE (labelled second layer)
# --------------------------------------------------------------------------

class NeuralSDE:
    """
    Wraps neural_sde. Fits at daily frequency where the package is
    calibrated, simulates daily, then aggregates to annual.

    IMPORTANT — drift is NOT taken from the model. The package's own
    documentation states that drift recovery is not usable at daily
    sampling frequency (signal-to-noise limit on a single path). Over a
    30-year horizon drift dominates everything, so leaving it to a learned
    black box would be both unreliable and untransparent.

    Instead: the model supplies the PATH SHAPE — volatility clustering,
    state dependence, the texture of drawdowns — and the annual log drift
    is then rescaled to a user-set assumption (`target_real_drift`). The
    user owns the number that matters; the model contributes the structure
    nobody else models.
    """

    name = "Neural SDE"
    is_default = False

    def __init__(self, daily_prices: np.ndarray, target_real_drift: float = 0.05,
                 steps_per_year: int = 252, model: str = "neural"):
        from neural_sde import fit
        self.steps_per_year = steps_per_year
        self.target_real_drift = float(target_real_drift)
        self.dt = 1.0 / steps_per_year
        self.fitted = fit(np.asarray(daily_prices, float), dt=self.dt, model=model)
        self.model_kind = self.fitted.kind

    def sample(self, n_paths: int, n_years: int, seed: int | None = None,
               batch: int = 250):
        from neural_sde import forecast
        horizon = n_years * self.steps_per_year
        out = np.empty((n_paths, n_years))
        done = 0
        b = 0
        while done < n_paths:
            k = min(batch, n_paths - done)
            fc = forecast(
                self.fitted, horizon=horizon, n_paths=k,
                antithetic=False, engine="euler",
                seed=None if seed is None else seed + b,
            )
            paths = np.asarray(fc.paths)
            if paths.shape[0] != k:          # (steps, paths) orientation
                paths = paths.T
            yearly = paths[:, ::self.steps_per_year][:, :n_years + 1]
            out[done:done + k] = yearly[:, 1:] / yearly[:, :-1] - 1.0
            done += k
            b += 1
            del fc, paths

        # Rescale annual log drift to the user's assumption, leaving the
        # path-shape structure the model learned intact.
        log_r = np.log1p(np.clip(out, -0.999, None))
        out = np.expm1(log_r - log_r.mean() + np.log1p(self.target_real_drift)
                       - 0.5 * log_r.var())
        return out

    def describe(self):
        return (f"{self.name}: fitted kind={self.model_kind}, "
                f"daily dt=1/{self.steps_per_year}, drift rescaled to "
                f"{self.target_real_drift:+.2%} real (user assumption, "
                f"NOT learned)")


# --------------------------------------------------------------------------
# Engine 3 — FCA prescribed rates (no dataset required)
# --------------------------------------------------------------------------

class FCAPrescribed:
    """
    Return engine built on the FCA's own standardised projection rates, so
    it needs NO historical dataset and therefore has NO licensing problem.

    COBS 13 Annex 2 2.3R — nominal rates a firm must use when projecting a
    personal pension:            lower 2%   intermediate 5%   higher 8%
    COBS 13 Annex 2 2.5R — price inflation:
                                 lower 0%   intermediate 2%   higher 4%

    Deflating each return by the INTERMEDIATE inflation rate (2%) gives the
    real rates this engine uses:

        lower  (1.02/1.02) - 1 = 0.00% real
        centre (1.05/1.02) - 1 = 2.94% real
        higher (1.08/1.02) - 1 = 5.88% real

    That pairing is an interpretation, not a rule — the Handbook prescribes
    the rates, not how to combine them. It is exposed as a parameter so the
    user can disagree with it.

    IMPORTANT: the FCA prescribes RETURNS, not VOLATILITY. `vol` below is
    an assumption with no regulatory backing, and it is the weakest number
    in this engine. It must be surfaced to the user, not buried.

    Source: https://handbook.fca.org.uk/handbook/COBS/13/Annex2.html
    Checked: 2026-08-15. Firms' prescribed rates are periodically reviewed —
    re-check against the live Handbook before relying on them.
    """

    name = "FCA prescribed rates"
    is_default = False

    NOMINAL = {"lower": 0.02, "centre": 0.05, "higher": 0.08}
    INFLATION = {"lower": 0.00, "centre": 0.02, "higher": 0.04}
    SOURCE = "FCA Handbook COBS 13 Annex 2 2.3R / 2.5R, checked 2026-08-15"

    def __init__(self, scenario: str = "centre", vol: float = 0.15,
                 inflation_scenario: str = "centre"):
        if scenario not in self.NOMINAL:
            raise ValueError(f"scenario must be one of {list(self.NOMINAL)}")
        self.scenario = scenario
        self.vol = float(vol)
        self.nominal = self.NOMINAL[scenario]
        self.inflation = self.INFLATION[inflation_scenario]
        self.real = (1 + self.nominal) / (1 + self.inflation) - 1

    def sample(self, n_paths: int, n_years: int, seed: int | None = None):
        rng = np.random.default_rng(seed)
        # Lognormal with the geometric mean pinned to self.real, so the
        # user's stated assumption is what the pot actually compounds at
        # rather than an arithmetic mean that quietly overshoots it.
        mu = np.log1p(self.real)
        z = rng.standard_normal((n_paths, n_years))
        z = (z - z.mean()) / z.std()          # remove sampling error in the mean
        return np.expm1(mu + self.vol * z)

    def scenarios(self, n_years: int):
        """The three deterministic FCA projections, real terms."""
        out = {}
        for k, nom in self.NOMINAL.items():
            r = (1 + nom) / (1 + self.inflation) - 1
            out[k] = np.full((1, n_years), r)
        return out

    def describe(self):
        return (f"{self.name}: {self.scenario} scenario, {self.nominal:.0%} "
                f"nominal less {self.inflation:.0%} inflation = "
                f"{self.real:+.2%} real; vol {self.vol:.0%} "
                f"(NOT prescribed — user assumption). {self.SOURCE}")
